### ISSUE TITLE
Coding classes for kids!

### ISSUE THREAD

**Issue by eugenetechorg** [EugTech/radio-show#19]
2/3/2019 14:43:06 | nikole@thatsupergirl.com | Coding classes for kids! |   |   | Nikole Gipps | https://codeeug.org | "The Eugene Coding Initiative was founded by Nikole Gipps to reduce the barriers to education and promote K through 12 computer science in the Eugene area. Nikole will be teaching several upcoming technology classes for kids in February and March through places like the Eugene Library and the Eugene Science Center. You can find more info by going to codeeug.org and clicking on activities!" |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by websupergirl** [comment]
The Eugene Coding Initiative was founded by Nikole Gipps to reduce the barriers to education and promote K through 12 computer science in the Eugene area. Nikole will be teaching several upcoming technology classes for kids and teens in March through the downtown branch of the Eugene Library. Classes are FREE and enrolling now! You can find more info by going to codeeug.org and clicking on events.
