### ISSUE TITLE
ArtSpark Purse Making Workshop for Lane Arts Council

### ISSUE THREAD

**Issue by juliejulieanderson** [EugTech/radio-show#24]
## SHORT Blurb about to read on the radio

Lane Arts Council is hosting a FREE "ArtSpark" Purse making Workshop to help you make an art-purse that will be auctioned off at the ArtSpark fundraiser on April 26, 2019. All proceeds will go towards supporting the Artist in Residence programs in 4J schools. More info on ArtSpark can be found at http://www.artsparkeugene.org/

The Purse Making event is FREE for individuals, community groups, and non-profits. We'll provide lots of funky vintage purses, fairy lights, other light-up tech, and art supplies. And bring your own purses, craft and tech supplies for yourself, and to share if you'd like.

You can take your purse home to finish it, and all purses will be due back on April 19th for a viewing party, before the auction.

## do you want to be on the show 7AM Thursday?
- [+ ] Yes

KUGN radio is located at 1200 Executive Pkwy, Ste 440, Eugene, OR 97401

## Event Date (When) (Events only)
March 6th, 2019, 5:30-7:30 p.m.

## Address if needed (Where)
942 Olive St, Eugene, OR 97401-3026, United States

## Contact name for more info
Julie Anderson, Organizer and Lane Arts Council Board Member

## Link to more info
Facebook Event here: https://www.facebook.com/events/451193262086998/

## would you like to be contacted for a video show segment?
- [+] Yes

There is a longer format TechTuesday LIVE video stream in the works

Thank you!  We're really glad your here :tada:

**Comment by juliejulieanderson** [comment]
Calling all artists, makers, techies and creative-curious fun seekers: come mash up art, tech and fashion with us, for a good cause! 

Lane Arts Council is hosting a FREE "ArtSpark" Purse making Workshop to help you make an art-purse that will be auctioned off at the ArtSpark fundraiser on April 26, 2019.  All proceeds will go towards supporting the Artist in Residence programs in 4J schools. More info on ArtSpark can be found at http://www.artsparkeugene.org/ 

The Purse Making event is FREE for individuals, community groups, and non-profits. We'll provide lots of funky vintage purses, fairy lights, other light-up tech, and art supplies. And bring your own purses, craft and tech supplies for yourself, and to share if you'd like.

You can take your purse home to finish it, and all purses will be due back on April 19th for a viewing party, before the auction.

Businesses who want to sponsor or create an ArtSpark purse with your work teams, please let us know! Sponsorship is available, and we can even match you up with an artist and/or technologist to create a custom purse with your logo or theme, if you'd like. 

Workshop Facilitators are Julie Anderson, a local artist and Lane Arts Council board member, and Kiki Prottsman, an educator, author, and vibrant YouTube personality will lead the workshop. 

This will be fun. And there will be snacks!

Please let us know if you're coming, so we can order enough light kits. And snacks. You can RSVP on the Facebook link (look for Lane Arts Council's page, it will be listed) or for more information email Julie at julieanderson@hotmail.com

**Comment by markdav-is** [comment]
nice work!
