### ISSUE TITLE
better blurb and some headshots

### ISSUE THREAD

**Issue by markdav-is** [EugTech/radio-show#25]
now that there is a web site https://audioboom.com/playlists/4626973-kugn-s-tech-talk-thursdays

the current blurb
Join KUGN's Dennis Nakata, Mark Davis from HP, Rory Fox from EDX Wireless, and special guests each week for special segments surrounding the tech world in Eugene/Springfield and beyond.

make it better
Join KUGN's Dennis Nakata, Rory Fox & Mark Davis from EugeneTech, and special guests each week for special segments surrounding the tech world in Eugene/Springfield (aka the SiliconShire) and beyond.

Ass some head shots here in the comments
- [x] rory
- [x] mark

this send this to jen
- [x] sent to jen
- [x] verify site is updated

**Comment by markdav-is** [comment]
![image](https://user-images.githubusercontent.com/311063/53674471-1be55300-3c43-11e9-95d4-87047176d2d8.png)

**Comment by markdav-is** [comment]
![hp-headshot](https://user-images.githubusercontent.com/311063/53674619-07ee2100-3c44-11e9-88ec-0718345a766d.jpg)

**Comment by roryfox** [comment]
![46836902_10161405125645227_6562915821645987840_o](https://user-images.githubusercontent.com/8084564/53746798-d13c2480-3e56-11e9-8372-c2c39f26d904.jpg)

**Comment by markdav-is** [comment]
@roryfox any edits on the bios?  I don't want to assume you identify as EugeneTech.  It's a bit of shameless self-promotion :)

**Comment by roryfox** [comment]
Looks like everything was updated on the site.  Closing until we want to update again...  (I should have waited for my new headshots!)
