### ISSUE TITLE
"Let's Design Eugene Town Square" LIVEShow

### ISSUE THREAD

**Issue by markdav-is** [EugTech/radio-show#59]
## Name of Topic or Event (What)
"Let's Design Eugene Town Square"

## SHORT Blurb about to read on the radio
(The radio show only 5 minutes long)
https://eugenetownsquare.org/

## Do you want talk live on the air, in the radio room 7AM Thursday?
- [X] Yes
- [ ] No

KUGN radio is located at 1200 Executive Pkwy, Ste 440, Eugene, OR 97401

## Event Date (When) (Events only)
wednesday june 19th

## Address if needed (Where)
the library 

## Contact name for more info

Joshua Evans [6:58 PM]
I sent an email to Julie@cogitopartners.com asking if she wanted to be on the show on the 18th 

To talk about "Let's Design Eugene Town Square"
## Would you like to be contacted for a video show segment?
- [X] Yes
- [ ] No

(There is a longer format TechTuesday LIVE video stream in the works)

Thank you!  We're really glad your here :tada:

**Comment by roryfox** [comment]
Julie or the designers will be on the show(s) prior to their big public event.
