### ISSUE TITLE
Steam Plant open house

### ISSUE THREAD

**Issue by markdav-is** [EugTech/radio-show#8]
steam plan open house is thursday

https://www.facebook.com/events/283738505650075/

**Comment by roryfox** [comment]
Located prominently along the banks of the Willamette River, and anchored at the southern end of the Downtown Riverfront site, the Steam Plant is an iconic representation of our community’s history and is ripe with possibility for the future. Currently, a local team of community leaders has created a vision for how the Steam Plant could be re-purposed and revitalized.

The local team, in partnership with the City of Eugene, invite you to join us at the EWEB Community Room for our official 'Open House' event. There, you will have an opportunity to learn more about the proposed project and provide feedback.

Event Schedule:
4:00pm Doors Open and Virtual Reality Tours Start
5:00pm Hello from the City of Eugene and local team
7:00pm  Thank you for coming!

Light appetizers and refreshments will be available. This is a no-cost event.
